<?php

$marcas = ['Dell', 'HP', 'Asus', 'Lenovo', 'Acer'];
$procesadores = ['Intel i3', 'Intel i5', 'Intel i7', 'Ryzen 3', 'Ryzen 5', 'Ryzen 7'];
$ram = ['4GB', '8GB', '16GB', '32GB'];
$discos = ['256GB SSD', '512GB SSD', '1TB HDD', '2TB HDD'];
$categorias = [1, 2, 4, 5, 6];
$comentarios_textos = [
    'Excelente producto.',
    'Muy buen rendimiento.',
    'La calidad podría mejorar.',
    'Me encanta, lo recomiendo.',
    'No cumplió mis expectativas.',
    'Ideal para el trabajo diario.',
    'Buen equipo para gaming.',
    'Perfecto para estudiantes.',
    'Precio justo y competitivo.',
    'Servicio postventa excelente.'
];
$nombres = [
    'Ana',
    'Luis',
    'Carlos',
    'Sofía',
    'Javier',
    'Valeria',
    'Miguel',
    'Lucía',
    'Kevin',
    'Fernanda',
    'Alejandro',
    'María',
    'Diego',
    'Isabel',
    'Ricardo',
    'Paola',
    'Fernando',
    'Gabriela',
    'Raúl',
    'Mónica',
    'Andrés',
    'Claudia',
    'Eduardo',
    'Patricia',
    'Sergio',
    'Daniela',
    'Juan',
    'Lorena',
    'Oscar',
    'Diana',
    'Héctor',
    'Carmen',
    'Víctor',
    'Elena',
    'Pablo',
    'Natalia',
    'Marcos',
    'Jessica',
    'Enrique',
    'Laura',
    'Roberto',
    'Verónica',
    'Alberto',
    'Carolina',
    'Salvador',
    'Jimena',
    'Manuel',
    'Alejandra',
    'Francisco',
    'Teresa'
];

$apellidos = [
    'Gómez',
    'Pérez',
    'Martínez',
    'López',
    'Ramírez',
    'Sánchez',
    'Ortega',
    'Morales',
    'Flores',
    'García',
    'Vázquez',
    'Torres',
    'Ramos',
    'Castillo',
    'Jiménez',
    'Mendoza',
    'Silva',
    'Reyes',
    'Cruz',
    'Domínguez',
    'Hernández',
    'Salazar',
    'Guerrero',
    'Molina',
    'Delgado',
    'Vega',
    'Castro',
    'Rojas',
    'Ortiz',
    'Fuentes',
    'Valdez',
    'Navarro',
    'Campos',
    'Soto',
    'Medina',
    'Aguilar',
    'Ponce',
    'Moreno',
    'Cortés',
    'Chávez',
    'Estrada',
    'Luna',
    'Gutiérrez',
    'Santana',
    'Marín',
    'Santos',
    'Benítez',
    'Vargas',
    'Carrillo'
];
